server:
  port: 9100
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hiberate:
        format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    locations: "classpath:db/migration"
    validate-on-migrate: false
  datasource:
    url: jdbc:postgresql://localhost:5433/db_microservice?escapeSyntaxCallMode=callIfNoReturn
    username: justclick
    password: justclick123
  main:
    allow-circular-references: true
